@ECHO OFF
IF NOT EXIST %USERPROFILE%\Settings.cmd (EXIT)
CALL %USERPROFILE%\Settings.cmd

REM ----------------------------------------------------------------------
REM Archive
REM ----------------------------------------------------------------------
SET OSU_LISTFILE=osu!.list
ECHO %OSU_DIR%\osu!.*.cfg>%OSU_LISTFILE%
ECHO %OSU_DIR%\Settings>>%OSU_LISTFILE%
ECHO %OSU_DIR%\Skins>>%OSU_LISTFILE%
ECHO %OSU_DIR%\*.db>>%OSU_LISTFILE%
IF NOT "%ARCHIVE_PASSWORD%"=="" SET ARCHIVE_OPT_PW=-p%ARCHIVE_PASSWORD% -mhe
CALL :FIND_BACKUPS
IF DEFINED BASE_ARCHIVE_FILE (
		CALL :UPDATE_7Z_FILE
	) ELSE (
		7z a -t7z %ARCHIVE_OPT_PW% %DOWNLOADS_DIR%\Osu!-Config-%yyyy%%mm%%dd%@%USERDOMAIN%.7z @%OSU_LISTFILE%
		REM 7z a -tzip %DOWNLOADS_DIR%\Osu!-Config-%yyyy%%mm%%dd%@%USERDOMAIN%.zip @%OSU_LISTFILE%
	)
DEL %OSU_LISTFILE%

PAUSE
EXPLORER %DOWNLOADS_DIR%
EXIT

:FIND_BACKUPS
	SET BACKUPS_DIR=B:\Backups
	FOR %%i IN ("%BACKUPS_DIR%\Osu!-Config-*@%USERDOMAIN%.7z") DO (
		ECHO SET BASE_ARCHIVE_FILE=%%~ni>a.cmd
		ECHO SET BASE_ARCHIVE_PATH=%%~fi>>a.cmd
	)
	IF EXIST a.cmd (
		CALL a.cmd
		DEL a.cmd
	)
	EXIT /B

:UPDATE_7Z_FILE
	IF "%OUTPUT_DIR%"=="" SET OUTPUT_DIR=%DESKTOP_DIR%
	IF NOT "%ARCHIVE_PASSWORD%"=="" SET ARCHIVE_OPT_PW=-p%ARCHIVE_PASSWORD% -mhe
	IF NOT DEFINED BASE_ARCHIVE_FILE SET /P BASE_ARCHIVE_FILE="Base Archive File: "
	SET UPDATE_7Z_FILE=%OUTPUT_DIR%\%BASE_ARCHIVE_FILE%_-_Update-%yyyy%%mm%%dd%.7z
	7z u %ARCHIVE_OPT_PW% %BASE_ARCHIVE_PATH% -u- -up0q3x2z0!%UPDATE_7Z_FILE% @%OSU_LISTFILE%
	7z l %ARCHIVE_OPT_PW% %UPDATE_7Z_FILE%
	EXIT /B
	