@ECHO OFF
REM ======================================================================
REM
REM                                Settings
REM
REM ======================================================================
REM DO NOT SET. SETLOCAL ENABLEDELAYEDEXPANSION



REM ======================================================================
REM
REM                                Main
REM
REM ======================================================================
SHIFT
SET FUNCTION=%~0%
IF "%FUNCTION%" EQU "" (
	SET /P FUNCTION="CALL FUNCTION:"
	CALL :!FUNCTION!
	ECHO RETURN:!ERRORLEVEL!
	PAUSE
) ELSE (
	GOTO :%FUNCTION%
)
GOTO :EOF



REM ======================================================================
REM
REM                                Function
REM
REM ======================================================================
REM CALL CMD_F_WAIT.cmd WAIT_JD2_FINISH [TIMEOUT]
:WAIT_JD2_FINISH
	SETLOCAL
	SET JD2_WAIT_TIMEOUT=%1
	SET LOOP_LOCK=%DESKTOP_DIR%\JD2.lock
	IF NOT DEFINED LOOP_LOCK EXIT /B
	ECHO Watch %LOOP_LOCK%
	SET TYR=0
	:LOOP_JD2_START
	IF NOT EXIST "%LOOP_LOCK%" GOTO :LOOP_JD2_END
	TIMEOUT /T 60
	SET /A TRY=%TRY%+1
	IF %TRY% GTR %JD2_WAIT_TIMEOUT% GOTO :LOOP_JD2_END
	GOTO :LOOP_JD2_START
	:LOOP_JD2_END
	ENDLOCAL
	EXIT /B


REM CALL CMD_F_WAIT.cmd WAIT_TIME_MIN [HOUR] [MIN]
:WAIT_TIME_MIN
	SETLOCAL
	SET WAIT_HOUR=%1
	SET WAIT_MIN=%2
	IF NOT DEFINED WAIT_HOUR SET WAIT_HOUR=0
	IF NOT DEFINED WAIT_MIN SET WAIT_MIN=0
	ECHO WAIT %WAIT_HOUR%H%WAIT_MIN%M
	SET /A T=3600*%WAIT_HOUR%+60*%WAIT_MIN%
	TIMEOUT /T %T%
	ENDLOCAL
	EXIT /B


REM CALL CMD_F_WAIT.cmd WAIT_CHROME_DOWNLOADING_AND_NOTIFY [TIMEOUT]
:WAIT_CHROME_DOWNLOADING_AND_NOTIFY
	SETLOCAL
	SET CHROME_WAIT_TIMEOUT=%1
	IF NOT DEFINED CHROME_WAIT_TIMEOUT SET CHROME_WAIT_TIMEOUT=180
	CALL :CHECK_CHROME_DONLOADING
	IF ERRORLEVEL 1 (
		ECHO CHROME IS NOT DOWNLOADING
		EXIT /B
	)
	CALL :WAIT_CRDOWNLOAD_FINISH %CHROME_WAIT_TIMEOUT%
	CALL :NOTIFY_SOUND %ERRORLEVEL%
	REM PAUSE
	ENDLOCAL
	EXIT /B
	
:CHECK_CHROME_DONLOADING
	IF EXIST %DOWNLOADS_DIR%\*.crdownload (
		DIR /B %DOWNLOADS_DIR%\*.crdownload
		EXIT /B 0
	)
	EXIT /B 1

REM CALL CMD_F_WAIT.cmd WAIT_CRDOWNLOAD_FINISH [TIMEOUT]
:WAIT_CRDOWNLOAD_FINISH
	SET CHROME_WAIT_TIMEOUT=%1
	IF NOT DEFINED CHROME_WAIT_TIMEOUT SET CHROME_WAIT_TIMEOUT=180
	SET TYR=0
	:LOOP_CHROME_START
	IF NOT DEFINED CHROME_WAIT_TIMEOUT GOTO :LOOP_CHROME_END
	REM CALL :CHECK_CHROME_DONLOADING
	CALL :CHECK_CHROME_DONLOADING_SIZE
	IF ERRORLEVEL 1 GOTO :LOOP_CHROME_END
	TIMEOUT /T 60
	SET /A TRY=%TRY%+1
	IF %TRY% GTR %CHROME_WAIT_TIMEOUT% GOTO :LOOP_CHROME_END
	GOTO :LOOP_CHROME_START
	:LOOP_CHROME_END
	EXIT /B %ERRORLEVEL%
	
:CHECK_CHROME_DONLOADING_SIZE
	IF NOT DEFINED FILE_SIZE_TOTAL SET FILE_SIZE_TOTAL=0
	SET BEFORE_FILE_SIZE_TOTAL=%FILE_SIZE_TOTAL%
	CALL :CHECK_FILESIZE_TOTAL %DOWNLOADS_DIR%\*.crdownload
	IF %FILE_SIZE_TOTAL% EQU 0 (
		ECHO .crdownload is not exist.
		EXIT /B 1
	)
	IF %BEFORE_FILE_SIZE_TOTAL% EQU %FILE_SIZE_TOTAL% (
		ECHO FILESIZE is Same. Downloading Stopped.
		EXIT /B 2
	)
	ECHO .crdownload is exist. %FILE_SIZE_TOTAL%byte
	EXIT /B 0
	
:CHECK_FILESIZE_TOTAL
	SETLOCAL
	SET TARGET=%1
	SET FILE_SIZE_TOTAL=0
	FOR %%i in (%TARGET%) DO (
		ECHO %%~zibyte %%~nxi
		SET FILE_SIZE_BYTE=%%~zi
		SET /A FILE_SIZE_TOTAL=!FILE_SIZE_TOTAL!+!FILE_SIZE_BYTE!
	)
	REM ECHO FILE_SIZE_TOTAL:%FILE_SIZE_TOTAL%
	ENDLOCAL
	EXIT /B

REM CALL :NOTIFY_SOUND [SOUND_TYPE]
:NOTIFY_SOUND
	SETLOCAL
	SET SOUND_TYPE=%1
	IF NOT DEFINED SOUND_TYPE EXIT /B
	ECHO SOUND_TYPE:%SOUND_TYPE%
	IF %SOUND_TYPE% EQU 1 (
		REM DOWNLOAD FINISHED
		SET SOUND_FILE="C:\Windows\Media\Ring01.wav"
	) ELSE (
		REM DOWNLOAD STOPPED.
		SET SOUND_FILE="C:\Windows\Media\Alarm01.wav"
		SET /A VOLUME=%VOLUME%+50
	)
	IF NOT DEFINED VOLUME SET VOLUME=20
	IF NOT DEFINED SOUND_LOOP SET SOUND_LOOP=3
	ffplay.exe -nodisp -volume %VOLUME% -loop %SOUND_LOOP% -autoexit %SOUND_FILE%
	ENDLOCAL
	EXIT /B


